#!/bin/bash


# https://stackoverflow.com/a/965072/5832619
PROBLEM=${1%%.*}

nasm -f elf64 "$PROBLEM.asm"

# https://stackoverflow.com/a/73468271/5832619
gcc -z noexecstack "$PROBLEM.o"

./a.out

rm "$PROBLEM.o"

